theme: minima

title: FIRST GITHUB PAGE!
author: Ilyass R
email: ilyasramzi26@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: i_do_not_use_twitter # DO NOT include the @ character, or else the build will fail!
github_username:  Ilyass-R # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
